sonar.projectKey=AltairaLabs_promptarena-deploy-omnia
sonar.organization=altairalabs

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

# Exclude HTTP client implementation and main entry point from coverage.
sonar.coverage.exclusions=**/client_real.go,**/main.go

sonar.sourceEncoding=UTF-8
